
CONFIG_HEAP_MEM_POOL_SIZE=16384
CONFIG_MAIN_STACK_SIZE=16384
CONFIG_SYSTEM_WORKQUEUE_STACK_SIZE=8192
CONFIG_NEWLIB_LIBC=y

# Enable Serial
CONFIG_SERIAL=y
CONFIG_UART_STM32=y
CONFIG_UART_INTERRUPT_DRIVEN=y

# Console over USART2 (ST-Link VCP)
CONFIG_CONSOLE=y
CONFIG_UART_CONSOLE=y

# Logging via UART backend
CONFIG_PRINTK=y
#CONFIG_LOG_BACKEND_UART=y
#CONFIG_LOG_BUFFER_SIZE=4096

# Useful during bring-up: include board name in logs and keep asserts on
CONFIG_ASSERT=y

CONFIG_LED=y
CONFIG_LED_GPIO=y

CONFIG_I2C=y
CONFIG_PWM=y
CONFIG_SPI=y
CONFIG_LED_STRIP=y
CONFIG_WS2812_PWM=y
CONFIG_GPIO_TCA6424A=y

# Core Flash and Storage support
CONFIG_FLASH=y
CONFIG_FLASH_MAP=y
CONFIG_STREAM_FLASH=y

# Enable LittleFS
CONFIG_FILE_SYSTEM=y
CONFIG_FILE_SYSTEM_LITTLEFS=y
CONFIG_FILE_SYSTEM_MKFS=y

# Enable NVS
CONFIG_NVS=y
CONFIG_FLASH_PAGE_LAYOUT=y
CONFIG_SPI_NOR_FLASH_LAYOUT_PAGE_SIZE=4096

# Modbus support
CONFIG_MODBUS=y
CONFIG_MODBUS_ROLE_SERVER=y
CONFIG_MODBUS_SERIAL=y

# Debugging flags
#CONFIG_I2C_LOG_LEVEL_DBG=n
#CONFIG_GPIO_LOG_LEVEL_DBG=n
#CONFIG_SPI_LOG_LEVEL_DBG=n
# CONFIG_THREAD_MONITOR=y
# CONFIG_THREAD_NAME=y

# Optimzations
CONFIG_LOG=y
# CONFIG_LINKER_ORPHAN_SECTION_WARN=y
# CONFIG_CBPRINTF_NANO=y
# CONFIG_BOOT_BANNER=n
