
#ifndef COLIBRI_RUNTIME_EVENTS_H
#define COLIBRI_RUNTIME_EVENTS_H

#define is_event_type(EVENT, TYPE) ((EVENT & 0xFF0000) == TYPE)
#define is_io_event(EVENT) ((EVENT & 0x1000000) == 0x1000000)
#define is_user_event(EVENT) ((EVENT & 0x1000000) == 0x0)
#define create_io_event(SLOT, EVENT_TYPE, EVENT_ID) (SLOT<<25 | 1<<24 | EVENT_TYPE<<16 | EVENT_ID)
#define create_user_event(EVENT_TYPE, EVENT_ID) (EVENT_TYPE<<16 | EVENT_ID)

#define COLIBRI_EVENT_TYPE_UNKNOWN            0x00
#define COLIBRI_EVENT_TYPE_TIME_PERIOD        0x01
#define COLIBRI_EVENT_TYPE_TIME               0x02
#define COLIBRI_EVENT_TYPE_COUNTER            0x03
#define COLIBRI_EVENT_TYPE_ERROR_CODE         0x04
#define COLIBRI_EVENT_TYPE_MEASURED_VALUE     0x05
#define COLIBRI_EVENT_TYPE_COMPUTED_VALUE     0x06
#define COLIBRI_EVENT_TYPE_SETPOINT           0x07
#define COLIBRI_EVENT_TYPE_MIN_VALUE          0x08
#define COLIBRI_EVENT_TYPE_MAX_VALUE          0x09
#define COLIBRI_EVENT_TYPE_LOW_THRESHOLD      0x0A
#define COLIBRI_EVENT_TYPE_HIGH_THRESHOLD     0x0B
#define COLIBRI_EVENT_TYPE_RUN_INDICATION     0x0C
#define COLIBRI_EVENT_TYPE_ALARM_INDICATION   0x0D

#endif //COLIBRI_RUNTIME_EVENTS_H
