
#ifndef COLIBRI_RUNTIME_MANAGEMENT_H
#define COLIBRI_RUNTIME_MANAGEMENT_H

#define EEPROM_MANAGEMENT_GROUP_ID (MGMT_GROUP_ID_PERUSER + 0)
#define IO_TEST_MANAGEMENT_GROUP_ID (MGMT_GROUP_ID_PERUSER + 1)

int management_initialize();

#endif
